# GitGuardian configuration
# https://docs.gitguardian.com/ggshield-docs/configuration

version: 2

secret:
  # Ignore test files which contain test credentials (not real secrets)
  ignored_paths:
    - "**/tests/**"
    - "**/testthat/**"
    - "**/*.test.ts"
    - "**/*.test.js"
    - "**/*.spec.ts"
    - "**/*.spec.js"
    - "**/test-*.R"
    - "**/helper-*.R"
    - "**/__tests__/**"
    - "**/__mocks__/**"
    - "**/fixtures/**"
    - ".env.example"
    - "*.example"

  # Ignore specific test passwords that are not real secrets
  ignored_matches:
    - name: test_password_patterns
      match: "NewTest1!"
    - name: test_password_patterns
      match: "FirstPw1!"
    - name: test_password_patterns
      match: "SecondPw2!"
    - name: test_password_patterns
      match: "password1salt1"
