export type DocsScreenshotAction =
  | { type: 'click'; selector: string }
  | { type: 'fill'; selector: string; value: string; sensitive?: boolean }
  | { type: 'press'; key: string }
  | { type: 'hover'; selector: string }
  | { type: 'waitFor'; selector: string }
  | { type: 'callHelper'; name: string; args?: Record<string, unknown> };

export type DocsScreenshotAnnotation = {
  selector: string;
  mode: 'box' | 'dot' | 'callout';
  label?: string;
  number?: number;
};

export type DocsScreenshot = {
  slug: string;
  output: string;
  docRefs: string[];
  route?: string;
  url?: string;
  baseURL?: 'app' | 'api' | string;
  viewport: { width: number; height: number };
  authRole?: 'admin' | 'curator' | 'reviewer' | 'user';
  preSetup?: string;
  setup?: string;
  actions?: DocsScreenshotAction[];
  waitFor?: string;
  locator?: string;
  fullPage?: boolean;
  clip?: { x: number; y: number; width: number; height: number };
  maskSelectors?: string[];
  annotations?: DocsScreenshotAnnotation[];
};

export const docsScreenshots: DocsScreenshot[] = [
  {
    slug: 'home',
    output: 'documentation/static/img/generated/home.png',
    docRefs: ['documentation/02-web-tool.qmd#landing-page'],
    route: '/',
    viewport: { width: 1440, height: 900 },
    waitFor: 'main',
    fullPage: true,
  },
  {
    slug: 'nav-tables-dropdown',
    output: 'documentation/static/img/generated/nav-tables-dropdown.png',
    docRefs: ['documentation/02-web-tool.qmd#main-navigation-menu'],
    route: '/',
    viewport: { width: 1440, height: 520 },
    setup: 'openTablesMenu',
    waitFor: 'main',
    fullPage: false,
    clip: { x: 0, y: 0, width: 1440, height: 260 },
    annotations: [
      { selector: '.dropdown-menu.show', mode: 'box', label: 'Tables' },
      { selector: '.dropdown-menu.show', mode: 'callout', number: 1, label: 'Table views' },
    ],
  },
  {
    slug: 'nav-analyses-dropdown',
    output: 'documentation/static/img/generated/nav-analyses-dropdown.png',
    docRefs: ['documentation/02-web-tool.qmd#main-navigation-menu'],
    route: '/',
    viewport: { width: 1440, height: 560 },
    setup: 'openAnalysesMenu',
    waitFor: 'main',
    fullPage: false,
    clip: { x: 0, y: 0, width: 1440, height: 320 },
    annotations: [
      { selector: '.dropdown-menu.show', mode: 'box', label: 'Analyses' },
      { selector: '.dropdown-menu.show', mode: 'callout', number: 1, label: 'Analysis routes' },
    ],
  },
  {
    slug: 'nav-help-dropdown',
    output: 'documentation/static/img/generated/nav-help-dropdown.png',
    docRefs: ['documentation/02-web-tool.qmd#main-navigation-menu'],
    route: '/',
    viewport: { width: 1440, height: 520 },
    setup: 'openHelpMenu',
    waitFor: 'main',
    fullPage: false,
    clip: { x: 0, y: 0, width: 1440, height: 260 },
    annotations: [
      { selector: '.dropdown-menu.show', mode: 'box', label: 'Help' },
      { selector: '.dropdown-menu.show', mode: 'callout', number: 1, label: 'About and docs' },
    ],
  },
  {
    slug: 'nav-search-non-home',
    output: 'documentation/static/img/generated/nav-search-non-home.png',
    docRefs: ['documentation/02-web-tool.qmd#main-navigation-menu'],
    route: '/Entities',
    viewport: { width: 1440, height: 520 },
    setup: 'tablePage',
    waitFor: 'main',
    fullPage: false,
    clip: { x: 0, y: 0, width: 1440, height: 180 },
    annotations: [
      { selector: '.app-navbar__search', mode: 'box', label: 'Search' },
      { selector: '.app-navbar__search', mode: 'callout', number: 1, label: 'Navbar search' },
      { selector: '.app-navbar__login', mode: 'callout', number: 2, label: 'Login link' },
    ],
  },
  {
    slug: 'nav-authenticated-admin',
    output: 'documentation/static/img/generated/nav-authenticated-admin.png',
    docRefs: ['documentation/02-web-tool.qmd#main-navigation-menu'],
    route: '/Entities',
    viewport: { width: 1440, height: 520 },
    authRole: 'admin',
    setup: 'openUserMenu',
    waitFor: 'main',
    fullPage: false,
    clip: { x: 0, y: 0, width: 1440, height: 270 },
    annotations: [
      { selector: '.app-navbar__account', mode: 'box', label: 'Authenticated navigation' },
      { selector: '.dropdown-menu.show', mode: 'callout', number: 1, label: 'User menu' },
    ],
  },
  {
    slug: 'footer-desktop',
    output: 'documentation/static/img/generated/footer-desktop.png',
    docRefs: ['documentation/02-web-tool.qmd#footer-navigation-menu'],
    route: '/',
    viewport: { width: 1440, height: 900 },
    waitFor: 'main',
    locator: '.app-footer__bar',
    annotations: [
      { selector: '.disclaimer-indicator__btn', mode: 'callout', number: 1, label: 'Policy' },
      { selector: '[aria-label="api-link"]', mode: 'callout', number: 2, label: 'API' },
    ],
  },
  {
    slug: 'entities-table',
    output: 'documentation/static/img/generated/entities-table.png',
    docRefs: ['documentation/02-web-tool.qmd#entities-table'],
    route: '/Entities',
    viewport: { width: 1440, height: 900 },
    setup: 'tablePage',
    waitFor: 'table',
    fullPage: true,
  },
  {
    slug: 'genes-table',
    output: 'documentation/static/img/generated/genes-table.png',
    docRefs: ['documentation/02-web-tool.qmd#genes-table'],
    route: '/Genes',
    viewport: { width: 1440, height: 900 },
    setup: 'tablePage',
    waitFor: 'table',
    fullPage: true,
  },
  {
    slug: 'phenotypes-table',
    output: 'documentation/static/img/generated/phenotypes-table.png',
    docRefs: ['documentation/02-web-tool.qmd#phenotypes-table'],
    route:
      '/Phenotypes?sort=entity_id&filter=all%28modifier_phenotype_id%2CHP%3A0001263%29&page_size=10',
    viewport: { width: 1440, height: 900 },
    setup: 'phenotypesTable',
    waitFor: 'table',
    fullPage: true,
    annotations: [
      {
        selector: '.phenotype-select-control',
        mode: 'callout',
        number: 1,
        label: 'Phenotype filter',
      },
      { selector: '.logic-toggle', mode: 'callout', number: 2, label: 'AND/OR logic' },
    ],
  },
  {
    slug: 'table-toolbar-actions',
    output: 'documentation/static/img/generated/table-toolbar-actions.png',
    docRefs: ['documentation/02-web-tool.qmd#phenotypes-table'],
    route: '/Entities',
    viewport: { width: 1440, height: 680 },
    setup: 'tablePage',
    waitFor: 'table',
    fullPage: false,
    clip: { x: 0, y: 0, width: 1440, height: 360 },
    annotations: [
      { selector: '.download-buttons', mode: 'box', label: 'Toolbar actions' },
      {
        selector: '.download-buttons button[aria-label="Copy link to this page"]',
        mode: 'callout',
        number: 1,
        label: 'Copy link',
      },
      {
        selector: '.download-buttons button[aria-label*="remove all filters" i]',
        mode: 'callout',
        number: 2,
        label: 'Clear filters',
      },
    ],
  },
  {
    slug: 'panels-table',
    output: 'documentation/static/img/generated/panels-table.png',
    docRefs: ['documentation/02-web-tool.qmd#panels-table'],
    route: '/Panels/All/All',
    viewport: { width: 1440, height: 900 },
    setup: 'tablePage',
    waitFor: 'table',
    fullPage: true,
    annotations: [
      {
        selector: '.panels-table__toolbar-row',
        mode: 'callout',
        number: 1,
        label: 'Panel controls',
      },
      { selector: '.table-shell__actions', mode: 'callout', number: 2, label: 'Download' },
    ],
  },
  {
    slug: 'table-entry-badges',
    output: 'documentation/static/img/generated/table-entry-badges.png',
    docRefs: ['documentation/02-web-tool.qmd#single-entry-pages'],
    route: '/Entities',
    viewport: { width: 1440, height: 680 },
    setup: 'tablePage',
    waitFor: 'table',
    fullPage: false,
    clip: { x: 0, y: 170, width: 1440, height: 360 },
    annotations: [
      { selector: 'a[href="/Entities/123"]', mode: 'callout', number: 1, label: 'Entity page' },
      { selector: 'a[href="/Genes/HGNC:20153"]', mode: 'callout', number: 2, label: 'Gene page' },
      {
        selector: 'a[href="/Ontology/MONDO:0100038"]',
        mode: 'callout',
        number: 3,
        label: 'Ontology page',
      },
    ],
  },
  {
    slug: 'gene-detail-chd8',
    output: 'documentation/static/img/generated/gene-detail-chd8.png',
    docRefs: ['documentation/02-web-tool.qmd#gene-page'],
    route: '/Genes/CHD8',
    viewport: { width: 1440, height: 900 },
    setup: 'geneDetailPage',
    waitFor: 'main',
    fullPage: true,
  },
  {
    slug: 'entity-detail-123',
    output: 'documentation/static/img/generated/entity-detail-123.png',
    docRefs: ['documentation/02-web-tool.qmd#entity-page'],
    route: '/Entities/123',
    viewport: { width: 1440, height: 900 },
    waitFor: 'main',
    fullPage: true,
  },
  {
    slug: 'ontology-detail',
    output: 'documentation/static/img/generated/ontology-detail.png',
    docRefs: ['documentation/02-web-tool.qmd#disease-ontology'],
    route: '/Ontology/MONDO:0100038',
    viewport: { width: 1440, height: 900 },
    setup: 'ontologyDetail',
    waitFor: 'main',
    fullPage: true,
  },
  {
    slug: 'curation-comparisons-overview',
    output: 'documentation/static/img/generated/curation-comparisons-overview.png',
    docRefs: ['documentation/02-web-tool.qmd#compare-curations'],
    route: '/CurationComparisons',
    viewport: { width: 1440, height: 900 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'curationComparison',
    fullPage: false,
  },
  {
    slug: 'curation-comparisons-similarity',
    output: 'documentation/static/img/generated/curation-comparisons-similarity.png',
    docRefs: ['documentation/02-web-tool.qmd#compare-curations'],
    route: '/CurationComparisons/Similarity',
    viewport: { width: 1440, height: 900 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'curationSimilarity',
    fullPage: false,
    locator: '.similarity-panel',
  },
  {
    slug: 'curation-comparisons-table',
    output: 'documentation/static/img/generated/curation-comparisons-table.png',
    docRefs: ['documentation/02-web-tool.qmd#compare-curations'],
    route: '/CurationComparisons/Table',
    viewport: { width: 1440, height: 900 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'tablePage',
    fullPage: false,
  },
  {
    slug: 'phenotype-correlations-correlogram',
    output: 'documentation/static/img/generated/phenotype-correlations-correlogram.png',
    docRefs: ['documentation/02-web-tool.qmd#correlate-phenotypes'],
    route: '/PhenotypeCorrelations',
    viewport: { width: 1440, height: 900 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'phenotypeCorrelogram',
    fullPage: false,
  },
  {
    slug: 'phenotype-correlations-counts',
    output: 'documentation/static/img/generated/phenotype-correlations-counts.png',
    docRefs: ['documentation/02-web-tool.qmd#correlate-phenotypes'],
    route: '/PhenotypeCorrelations/PhenotypeCounts',
    viewport: { width: 1440, height: 900 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'phenotypeCounts',
    fullPage: false,
  },
  {
    slug: 'phenotype-correlations-clusters',
    output: 'documentation/static/img/generated/phenotype-correlations-clusters.png',
    docRefs: ['documentation/02-web-tool.qmd#correlate-phenotypes'],
    route: '/PhenotypeCorrelations/PhenotypeClusters',
    viewport: { width: 1440, height: 900 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'phenotypeClusters',
    fullPage: false,
  },
  {
    slug: 'entries-over-time',
    output: 'documentation/static/img/generated/entries-over-time.png',
    docRefs: ['documentation/02-web-tool.qmd#entries-over-time'],
    route: '/EntriesOverTime',
    viewport: { width: 1440, height: 900 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'entriesOverTime',
    fullPage: false,
  },
  {
    slug: 'publications-ndd',
    output: 'documentation/static/img/generated/publications-ndd.png',
    docRefs: ['documentation/02-web-tool.qmd#ndd-publications'],
    route: '/PublicationsNDD',
    viewport: { width: 1440, height: 900 },
    waitFor: 'main',
    fullPage: true,
  },
  {
    slug: 'functional-clusters',
    output: 'documentation/static/img/generated/functional-clusters.png',
    docRefs: ['documentation/02-web-tool.qmd#functional-clusters'],
    route: '/GeneNetworks',
    viewport: { width: 1440, height: 900 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'functionalClusters',
    fullPage: false,
  },
  {
    slug: 'helper-feedback-menu',
    output: 'documentation/static/img/generated/helper-feedback-menu.png',
    docRefs: ['documentation/02-web-tool.qmd#help-feedback'],
    route: '/Entities',
    viewport: { width: 1440, height: 900 },
    setup: 'openHelperBadge',
    waitFor: 'main',
    fullPage: false,
    maskSelectors: ['.tooltip'],
    annotations: [
      { selector: '.float', mode: 'box', label: 'Help menu' },
      { selector: '.dropdown-menu.show', mode: 'box', label: 'Feedback actions' },
    ],
  },
  {
    slug: 'login-page',
    output: 'documentation/static/img/generated/login-page.png',
    docRefs: [
      'documentation/02-web-tool.qmd#login-page',
      'documentation/06-re-review-instructions.qmd#login',
    ],
    route: '/Login',
    viewport: { width: 1280, height: 900 },
    waitFor: 'form',
    fullPage: true,
  },
  {
    slug: 'login-auth-error-toast',
    output: 'documentation/static/img/generated/login-auth-error-toast.png',
    docRefs: ['documentation/02-web-tool.qmd#reporting-bugs-problems-and-making-feature-requests'],
    route: '/Login',
    viewport: { width: 1280, height: 900 },
    setup: 'loginAuthError',
    waitFor: 'form',
    fullPage: true,
    annotations: [{ selector: '.toast, [role="alert"]', mode: 'box', label: 'Visible error' }],
  },
  {
    slug: 'register-page',
    output: 'documentation/static/img/generated/register-page.png',
    docRefs: ['documentation/02-web-tool.qmd#register-user-page'],
    route: '/Register',
    viewport: { width: 1280, height: 900 },
    waitFor: 'form',
    fullPage: true,
  },
  {
    slug: 'password-reset-page',
    output: 'documentation/static/img/generated/password-reset-page.png',
    docRefs: ['documentation/02-web-tool.qmd#reset-password-page'],
    route: '/PasswordReset',
    viewport: { width: 1280, height: 900 },
    setup: 'passwordResetPage',
    waitFor: 'form',
    fullPage: true,
  },
  {
    slug: 'mobile-home',
    output: 'documentation/static/img/generated/mobile-home.png',
    docRefs: ['documentation/02-web-tool.qmd#mobile-website'],
    route: '/',
    viewport: { width: 390, height: 844 },
    waitFor: 'main',
    fullPage: true,
  },
  {
    slug: 'mobile-navbar-open',
    output: 'documentation/static/img/generated/mobile-navbar-open.png',
    docRefs: ['documentation/02-web-tool.qmd#mobile-website'],
    route: '/',
    viewport: { width: 390, height: 844 },
    setup: 'openMobileNavbar',
    waitFor: 'main',
    fullPage: false,
  },
  {
    slug: 'mobile-footer-open',
    output: 'documentation/static/img/generated/mobile-footer-open.png',
    docRefs: ['documentation/02-web-tool.qmd#mobile-website'],
    route: '/',
    viewport: { width: 390, height: 844 },
    setup: 'openMobileFooter',
    waitFor: 'main',
    locator: '.app-footer__bar',
  },
  {
    slug: 'mobile-entities-table',
    output: 'documentation/static/img/generated/mobile-entities-table.png',
    docRefs: ['documentation/02-web-tool.qmd#mobile-website'],
    route: '/Entities',
    viewport: { width: 390, height: 844 },
    setup: 'mobileTablePage',
    waitFor: 'main',
    fullPage: true,
  },
  {
    slug: 'mobile-landscape-analysis',
    output: 'documentation/static/img/generated/mobile-landscape-analysis.png',
    docRefs: ['documentation/02-web-tool.qmd#mobile-website'],
    route: '/PhenotypeCorrelations',
    viewport: { width: 844, height: 390 },
    preSetup: 'analysisDataMocks',
    waitFor: 'main',
    setup: 'phenotypeCorrelogram',
    fullPage: false,
  },
  {
    slug: 'pwa-mobile-shell',
    output: 'documentation/static/img/generated/pwa-mobile-shell.png',
    docRefs: ['documentation/02-web-tool.qmd#progressive-web-app-pwa'],
    route: '/',
    viewport: { width: 390, height: 844 },
    waitFor: 'main',
    fullPage: false,
  },
  {
    slug: 'reviewer-review-page',
    output: 'documentation/static/img/generated/reviewer-review-page.png',
    docRefs: ['documentation/06-re-review-instructions.qmd#review-page'],
    route: '/Review',
    viewport: { width: 1440, height: 900 },
    authRole: 'reviewer',
    setup: 'reviewerReviewPage',
    waitFor: 'main',
    fullPage: true,
  },
  {
    slug: 'reviewer-modify-review-modal',
    output: 'documentation/static/img/generated/reviewer-modify-review-modal.png',
    docRefs: ['documentation/06-re-review-instructions.qmd#new-review-edit'],
    route: '/Review',
    viewport: { width: 1440, height: 900 },
    authRole: 'reviewer',
    setup: 'reviewerReviewPage',
    actions: [{ type: 'callHelper', name: 'openFirstReviewEditModal' }],
    waitFor: 'main',
    fullPage: false,
    locator: '.modal.show',
  },
  {
    slug: 'api-swagger-overview',
    output: 'documentation/static/img/generated/api-swagger-overview.png',
    docRefs: ['documentation/03-api.qmd#endpoints'],
    baseURL: 'app',
    url: '/API',
    viewport: { width: 1440, height: 900 },
    setup: 'swaggerOverview',
    waitFor: '.swagger-ui',
    fullPage: true,
  },
  {
    slug: 'api-swagger-auth',
    output: 'documentation/static/img/generated/api-swagger-auth.png',
    docRefs: ['documentation/03-api.qmd#authentication-and-authorization'],
    baseURL: 'app',
    url: '/API',
    viewport: { width: 1440, height: 900 },
    setup: 'swaggerAuthScreen',
    waitFor: '.swagger-ui',
    fullPage: true,
  },
];
