# functions/analysis-snapshot-dependencies.R
#
# Dependency-bound construction for analysis snapshots derived from cluster axes.

if (!exists("%||%", mode = "function")) {
  `%||%` <- function(x, y) if (is.null(x)) y else x
}

#' Load one active cluster snapshot as an immutable dependency.
#'
#' A phenotype-functional correlation cannot be safely regenerated by calling the
#' clustering functions again: even with the same source-data version, a later
#' cluster refresh can change membership between the correlation calculation and
#' its display. This helper makes the two active cluster snapshots the sole input
#' to the dependent correlation snapshot.
#' @noRd
analysis_snapshot_load_cluster_dependency <- function(analysis_type,
                                                      params,
                                                      cluster_snapshot_loader = analysis_snapshot_get_public,
                                                      conn = NULL) {
  normalized <- analysis_snapshot_normalize_params(analysis_type, params)
  snapshot <- cluster_snapshot_loader(
    normalized$analysis_type,
    normalized$parameter_hash,
    conn = conn
  )
  if (is.null(snapshot) || !identical(snapshot$status_code %||% "", "available")) {
    status <- snapshot$status_code %||% "snapshot_missing"
    stop(
      sprintf(
        "Dependency snapshot %s is not available (status: %s)",
        normalized$analysis_type,
        status
      ),
      call. = FALSE
    )
  }

  manifest <- tibble::as_tibble(snapshot$manifest %||% tibble::tibble())
  members <- tibble::as_tibble(snapshot$cluster_members %||% tibble::tibble())
  required_manifest <- c("snapshot_id", "payload_hash")
  required_members <- c("cluster_kind", "cluster_id", "hgnc_id")
  if (nrow(manifest) != 1L || !all(required_manifest %in% names(manifest))) {
    stop(
      sprintf("Dependency snapshot %s has incomplete manifest provenance", normalized$analysis_type),
      call. = FALSE
    )
  }
  if (!all(required_members %in% names(members))) {
    stop(
      sprintf("Dependency snapshot %s has incomplete cluster membership", normalized$analysis_type),
      call. = FALSE
    )
  }

  snapshot_id <- suppressWarnings(as.integer(manifest$snapshot_id[[1]]))
  payload_hash <- as.character(manifest$payload_hash[[1]])
  if (is.na(snapshot_id) || !nzchar(payload_hash)) {
    stop(
      sprintf("Dependency snapshot %s has invalid manifest provenance", normalized$analysis_type),
      call. = FALSE
    )
  }

  list(
    members = members,
    dependency = list(snapshot_id = snapshot_id, payload_hash = payload_hash)
  )
}

#' Build the phenotype-functional correlation matrix from active cluster snapshots.
#'
#' @noRd
analysis_snapshot_build_dependency_bound_pc_fc_correlation <- function(
    cluster_snapshot_loader = analysis_snapshot_get_public,
    conn = NULL) {
  functional <- analysis_snapshot_load_cluster_dependency(
    "functional_clusters",
    list(algorithm = "leiden"),
    cluster_snapshot_loader = cluster_snapshot_loader,
    conn = conn
  )
  phenotype <- analysis_snapshot_load_cluster_dependency(
    "phenotype_clusters",
    list(),
    cluster_snapshot_loader = cluster_snapshot_loader,
    conn = conn
  )

  normalize_members <- function(rows, kind, prefix) {
    rows <- dplyr::filter(
      rows,
      .data$cluster_kind == kind,
      !is.na(.data$cluster_id),
      !is.na(.data$hgnc_id),
      nzchar(.data$hgnc_id)
    )
    dplyr::transmute(
      rows,
      hgnc_id = as.character(.data$hgnc_id),
      cluster = paste0(prefix, as.character(.data$cluster_id))
    ) |>
      dplyr::distinct()
  }

  all_clusters <- dplyr::bind_rows(
    normalize_members(functional$members, "functional", "fc_"),
    normalize_members(phenotype$members, "phenotype", "pc_")
  )
  if (nrow(all_clusters) == 0L) {
    stop("Cluster snapshot dependencies contain no usable memberships", call. = FALSE)
  }

  cluster_matrix <- all_clusters |>
    dplyr::mutate(has_hgnc_id = 1L) |>
    tidyr::pivot_wider(
      names_from = cluster,
      values_from = has_hgnc_id,
      values_fill = 0L
    ) |>
    dplyr::select(-hgnc_id)
  if (ncol(cluster_matrix) == 0L) {
    stop("Cluster snapshot dependencies contain no cluster columns", call. = FALSE)
  }

  correlation_matrix <- round(stats::cor(cluster_matrix), 2)
  rows <- as.data.frame(as.table(correlation_matrix), stringsAsFactors = FALSE) |>
    tibble::as_tibble() |>
    dplyr::transmute(
      x = as.character(.data$Var1),
      y = as.character(.data$Var2),
      value = as.numeric(.data$Freq)
    )

  list(
    rows = rows,
    dependencies = list(
      functional_clusters = functional$dependency,
      phenotype_clusters = phenotype$dependency
    )
  )
}

#' Return the active manifest provenance for one cluster-snapshot preset.
#' @noRd
analysis_snapshot_active_cluster_manifest <- function(analysis_type, params, conn = NULL) {
  normalized <- analysis_snapshot_normalize_params(analysis_type, params)
  db_execute_query(
    paste(
      "SELECT snapshot_id, payload_hash",
      "FROM analysis_snapshot_manifest",
      "WHERE analysis_type = ?",
      "AND parameter_hash = ?",
      "AND public_ready = 1",
      "AND status = 'public_ready'",
      "ORDER BY activated_at DESC, snapshot_id DESC",
      "LIMIT 1"
    ),
    unname(list(normalized$analysis_type, normalized$parameter_hash)),
    conn = conn
  )
}

#' Read dependency lineage from a correlation manifest's source-version record.
#' @noRd
analysis_snapshot_manifest_dependencies <- function(manifest) {
  manifest <- tibble::as_tibble(manifest %||% tibble::tibble())
  if (nrow(manifest) != 1L || !("source_versions_json" %in% names(manifest))) {
    return(NULL)
  }
  raw <- as.character(manifest$source_versions_json[[1]] %||% "")
  if (!nzchar(raw)) {
    return(NULL)
  }
  parsed <- tryCatch(
    jsonlite::fromJSON(raw, simplifyVector = FALSE),
    error = function(e) NULL
  )
  dependencies <- parsed$dependencies %||% NULL
  if (!is.list(dependencies)) {
    return(NULL)
  }
  dependencies
}

#' Verify that a phenotype-functional snapshot still matches active cluster axes.
#'
#' @noRd
analysis_snapshot_dependency_status_code <- function(
    manifest,
    active_manifest_loader = analysis_snapshot_active_cluster_manifest,
    conn = NULL) {
  manifest <- tibble::as_tibble(manifest %||% tibble::tibble())
  if (nrow(manifest) != 1L ||
      !identical(as.character(manifest$analysis_type[[1]] %||% ""), "phenotype_functional_correlations")) {
    return("available")
  }

  dependencies <- analysis_snapshot_manifest_dependencies(manifest)
  expected <- list(
    functional_clusters = list(algorithm = "leiden"),
    phenotype_clusters = list()
  )
  if (is.null(dependencies) || !identical(sort(names(dependencies)), sort(names(expected)))) {
    return("dependency_snapshot_mismatch")
  }

  for (analysis_type in names(expected)) {
    dependency <- dependencies[[analysis_type]]
    if (!is.list(dependency)) {
      return("dependency_snapshot_mismatch")
    }
    expected_id <- suppressWarnings(as.integer(dependency$snapshot_id %||% NA_integer_))
    expected_hash <- as.character(dependency$payload_hash %||% "")
    active <- tibble::as_tibble(
      active_manifest_loader(analysis_type, expected[[analysis_type]], conn = conn) %||% tibble::tibble()
    )
    if (nrow(active) != 1L || !all(c("snapshot_id", "payload_hash") %in% names(active))) {
      return("dependency_snapshot_mismatch")
    }
    active_id <- suppressWarnings(as.integer(active$snapshot_id[[1]]))
    active_hash <- as.character(active$payload_hash[[1]])
    if (is.na(expected_id) || !nzchar(expected_hash) ||
        is.na(active_id) || !nzchar(active_hash) ||
        !identical(expected_id, active_id) || !identical(expected_hash, active_hash)) {
      return("dependency_snapshot_mismatch")
    }
  }

  "available"
}
